
import { Property, Landlord, Application, Document, PropertyStatus, ApplicationStatus } from '@/types/database';

export const DEMO_LANDLORDS: Landlord[] = [
    {
        id: 'l1',
        name: 'Sarah Mitchell',
        email: 'sarah.m@example.com',
        phone: '416-555-0101',
        company_name: 'Mitchell Holdings',
        address: '123 Yonge St, Toronto, ON',
        notes: 'Prefers email communication. Very proactive with maintenance.',
        created_at: '2025-01-15T10:00:00Z',
        properties_count: 3
    },
    {
        id: 'l2',
        name: 'David Chen',
        email: 'david.chen@example.com',
        phone: '416-555-0102',
        company_name: 'Chen Properties Inc.',
        address: '456 Queen St W, Toronto, ON',
        notes: 'Looking to expand portfolio in Downtown.',
        created_at: '2025-01-10T09:30:00Z',
        properties_count: 2
    },
    {
        id: 'l3',
        name: 'Maria Rodriguez',
        email: 'maria.r@example.com',
        phone: '647-555-0103',
        company_name: null,
        address: '789 King St W, Toronto, ON',
        notes: 'Long-term client.',
        created_at: '2024-11-20T14:20:00Z',
        properties_count: 4
    },
    {
        id: 'l4',
        name: 'James Wilson',
        email: 'j.wilson@example.com',
        phone: '416-555-0104',
        company_name: 'Wilson Estates',
        address: '101 Bay St, Toronto, ON',
        notes: 'Requires approval for all expenses over $500.',
        created_at: '2024-12-05T11:45:00Z',
        properties_count: 2
    },
    {
        id: 'l5',
        name: 'Lisa Park',
        email: 'lisa.park@example.com',
        phone: '647-555-0105',
        company_name: null,
        address: '202 Dundas St W, Toronto, ON',
        notes: 'New client, 1 property.',
        created_at: '2026-01-02T16:15:00Z',
        properties_count: 1
    }
];

export const DEMO_PROPERTIES: Property[] = [
    {
        id: 'p1',
        landlord_id: 'l1',
        address: '15 Iceboat Terrace',
        unit_number: '3102',
        city: 'Toronto',
        neighborhood: 'CityPlace',
        rent: 2400,
        bedrooms: 1,
        bathrooms: 1,
        square_feet: 600,
        description: 'Modern 1BR corner unit with lake views. Floor to ceiling windows, sleek kitchen with integrated appliances.',
        amenities: ['Gym', 'Pool', 'Concierge', 'Balcony', 'In-suite Laundry'],
        lockbox_code: '1234',
        status: 'available',
        available_date: '2026-03-01',
        created_at: '2026-01-15T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80'],
        photos_relation: [],
        pet_policy: 'restricted',
        parking_included: false,
        utilities_included: ['water']
    },
    {
        id: 'p2',
        landlord_id: 'l1',
        address: '85 Queens Wharf Rd',
        unit_number: '1504',
        city: 'Toronto',
        neighborhood: 'CityPlace',
        rent: 2800,
        bedrooms: 2,
        bathrooms: 2,
        square_feet: 850,
        description: 'Spacious 2BR split layout. Large balcony, parking included. Steps to transit and grocery.',
        amenities: ['Gym', 'Pool', 'Parking', 'Concierge', 'Party Room'],
        lockbox_code: '5678',
        status: 'rented',
        available_date: '2026-02-01',
        created_at: '2026-01-10T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'allowed',
        parking_included: true,
        utilities_included: ['water', 'heat']
    },
    {
        id: 'p3',
        landlord_id: 'l1',
        address: '21 Nelson St',
        unit_number: '905',
        city: 'Toronto',
        neighborhood: 'Entertainment District',
        rent: 3100,
        bedrooms: 2,
        bathrooms: 2,
        square_feet: 900,
        description: 'Luxury boutique condo in the heart of the Entertainment District. High-end finishes.',
        amenities: ['Rooftop Terrace', 'Gym', 'Concierge', 'Guest Suites'],
        lockbox_code: '9988',
        status: 'pending',
        available_date: '2026-02-15',
        created_at: '2026-01-20T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'no_pets',
        parking_included: true,
        utilities_included: []
    },
    {
        id: 'p4',
        landlord_id: 'l2',
        address: '390 Cherry St',
        unit_number: '204',
        city: 'Toronto',
        neighborhood: 'Distillery District',
        rent: 2100,
        bedrooms: 1,
        bathrooms: 1,
        square_feet: 550,
        description: 'Loft-style unit in the historic Distillery District. Exposed concrete, 10ft ceilings.',
        amenities: ['Pool', 'Gym', 'Concierge', 'Bike Storage'],
        lockbox_code: '4321',
        status: 'available',
        available_date: '2026-02-01',
        created_at: '2026-01-25T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'allowed',
        parking_included: false,
        utilities_included: ['water', 'heat', 'hydro']
    },
    {
        id: 'p5',
        landlord_id: 'l2',
        address: '390 Cherry St',
        unit_number: 'PH04',
        city: 'Toronto',
        neighborhood: 'Distillery District',
        rent: 4200,
        bedrooms: 3,
        bathrooms: 2,
        square_feet: 1200,
        description: 'Stunning Penthouse with panoramic city and lake views. Wrap-around terrace.',
        amenities: ['Pool', 'Gym', 'Concierge', 'Parking', 'Terrace'],
        lockbox_code: '7777',
        status: 'rented',
        available_date: '2026-04-01',
        created_at: '2025-12-15T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'allowed',
        parking_included: true,
        utilities_included: []
    },
    {
        id: 'p6',
        landlord_id: 'l3',
        address: '11 Charlotte St',
        unit_number: '1401',
        city: 'Toronto',
        neighborhood: 'King West',
        rent: 2600,
        bedrooms: 1,
        bathrooms: 1,
        square_feet: 650,
        description: 'Sophisticated King West living. Stone counters, gas cooktop. Steps to best restaurants.',
        amenities: ['Outdoor Pool', 'Gym', 'Concierge', 'Lounge'],
        lockbox_code: '2468',
        status: 'available',
        available_date: '2026-02-10',
        created_at: '2026-01-28T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1484154218962-a1c002085d2f?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'restricted',
        parking_included: false,
        utilities_included: ['water']
    },
    {
        id: 'p7',
        landlord_id: 'l3',
        address: '500 Wellington St W',
        unit_number: '502',
        city: 'Toronto',
        neighborhood: 'King West',
        rent: 3400,
        bedrooms: 2,
        bathrooms: 2,
        square_feet: 1100,
        description: 'Boutique luxury building. Private elevator access, large terrace, premium appliances.',
        amenities: ['Concierge', 'Parking', 'Visitor Parking'],
        lockbox_code: '1357',
        status: 'pending',
        available_date: '2026-03-01',
        created_at: '2026-01-22T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1502005229762-cf1dbf06ba06?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'allowed',
        parking_included: true,
        utilities_included: ['water', 'gas']
    },
    {
        id: 'p8',
        landlord_id: 'l3',
        address: '629 King St W',
        unit_number: '810',
        city: 'Toronto',
        neighborhood: 'King West',
        rent: 1950,
        bedrooms: 1,
        bathrooms: 1,
        square_feet: 500,
        description: 'Efficient 1 bedroom layout. Exposed concrete ceilings, hardwood floors.',
        amenities: ['Gym', 'Concierge', 'Rooftop Pool'],
        lockbox_code: '0000',
        status: 'rented',
        available_date: '2026-05-01',
        created_at: '2025-11-28T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'no_pets',
        parking_included: false,
        utilities_included: ['water']
    },
    {
        id: 'p9',
        landlord_id: 'l3',
        address: '38 Niagara St',
        unit_number: '205',
        city: 'Toronto',
        neighborhood: 'King West',
        rent: 2300,
        bedrooms: 1,
        bathrooms: 1,
        square_feet: 620,
        description: 'Quiet street in busy King West. Park views, spacious bedroom.',
        amenities: ['Gym', 'Party Room', 'BBQ Area'],
        lockbox_code: '1111',
        status: 'available',
        available_date: '2026-02-01',
        created_at: '2026-01-18T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'allowed',
        parking_included: true,
        utilities_included: ['water']
    },
    {
        id: 'p10',
        landlord_id: 'l4',
        address: '1 Bloor St E',
        unit_number: '4502',
        city: 'Toronto',
        neighborhood: 'Yorkville',
        rent: 3800,
        bedrooms: 2,
        bathrooms: 2,
        square_feet: 950,
        description: 'Prestigious address at Yonge and Bloor. Direct subway access, high end finishes.',
        amenities: ['Indoor Pool', 'Outdoor Pool', 'Spa', 'Gym', 'Concierge'],
        lockbox_code: '8888',
        status: 'available',
        available_date: '2026-03-01',
        created_at: '2026-01-26T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1507089947368-19c1da97ee9f?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'restricted',
        parking_included: true,
        utilities_included: []
    },
    {
        id: 'p11',
        landlord_id: 'l4',
        address: '18 Yorkville Ave',
        unit_number: '1205',
        city: 'Toronto',
        neighborhood: 'Yorkville',
        rent: 2900,
        bedrooms: 1,
        bathrooms: 1,
        square_feet: 700,
        description: 'Classic Yorkville condo. Steps to high-end shopping and dining. Library and media room.',
        amenities: ['Concierge', 'Gym', 'Library', 'Terrace'],
        lockbox_code: '2222',
        status: 'rented',
        available_date: '2026-01-15',
        created_at: '2025-10-15T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'allowed',
        parking_included: true,
        utilities_included: ['water']
    },
    {
        id: 'p12',
        landlord_id: 'l5',
        address: '1900 Bayview Ave',
        unit_number: '304',
        city: 'Toronto',
        neighborhood: 'Bridle Path / Sunnybrook',
        rent: 3200,
        bedrooms: 2,
        bathrooms: 2,
        square_feet: 1150,
        description: 'Spacious unit in a quiet, leafy neighborhood. Renovated kitchen and large master.',
        amenities: ['Concierge', 'Gym', 'Gardens', 'Visitor Parking'],
        lockbox_code: '5555',
        status: 'available',
        available_date: '2026-02-15',
        created_at: '2026-01-24T12:00:00Z',
        photos: ['https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=800&q=80'],
        pet_policy: 'allowed',
        parking_included: true,
        utilities_included: ['water', 'hydro', 'cable']
    }
];

export const DEMO_APPLICANTS: Application[] = [
    {
        id: 'a1',
        property_id: 'p1',
        applicant_name: 'John Doe',
        applicant_email: 'john.doe@email.com',
        applicant_phone: '416-555-1001',
        status: 'new',
        created_at: '2026-01-28T10:00:00Z',
        current_address: 'Toronto, ON',
        employer: 'Tech Corp',
        monthly_income: 6000,
        move_in_date: '2026-03-01',
        num_occupants: 1,
        has_pets: false,
        pet_details: null,
        additional_notes: 'Looking for a quick move-in.',
        screening_status: 'pending',
        credit_score: null,
        background_check_passed: null,
        income_verified: null,
        screening_report_url: null,
        screening_completed_at: null,
        webhook_sent: false,
        webhook_sent_at: null,
        updated_at: '2026-01-28T10:00:00Z',
        agent_id: null,
        company_id: null
    },
    {
        id: 'a2',
        property_id: 'p1',
        applicant_name: 'Jane Smith',
        applicant_email: 'jane.smith@email.com',
        applicant_phone: '416-555-1002',
        status: 'screening',
        created_at: '2026-01-27T14:30:00Z',
        current_address: 'Mississauga, ON',
        employer: 'Bank of Canada',
        monthly_income: 7500,
        move_in_date: '2026-03-01',
        num_occupants: 1,
        has_pets: true,
        pet_details: '1 small cat',
        additional_notes: 'Excellent credit.',
        screening_status: 'submitted',
        credit_score: 780,
        background_check_passed: true,
        income_verified: true,
        screening_report_url: 'http://example.com/report',
        screening_completed_at: '2026-01-28T09:00:00Z',
        webhook_sent: false,
        webhook_sent_at: null,
        updated_at: '2026-01-28T09:00:00Z',
        agent_id: null,
        company_id: null
    },
    {
        id: 'a3',
        property_id: 'p6',
        applicant_name: 'Michael Brown',
        applicant_email: 'm.brown@email.com',
        applicant_phone: '647-555-1003',
        status: 'approved',
        created_at: '2026-01-25T11:00:00Z',
        current_address: 'Toronto, ON',
        employer: 'Law Firm LLP',
        monthly_income: 9000,
        move_in_date: '2026-02-15',
        num_occupants: 1,
        has_pets: false,
        pet_details: null,
        additional_notes: null,
        screening_status: 'completed',
        credit_score: 800,
        background_check_passed: true,
        income_verified: true,
        screening_report_url: 'http://example.com/report2',
        screening_completed_at: '2026-01-26T15:00:00Z',
        webhook_sent: false,
        webhook_sent_at: null,
        updated_at: '2026-01-26T16:00:00Z',
        agent_id: null,
        company_id: null
    },
    {
        id: 'a4',
        property_id: 'p6',
        applicant_name: 'Emily Davis',
        applicant_email: 'emily.d@email.com',
        applicant_phone: '647-555-1004',
        status: 'denied',
        created_at: '2026-01-25T13:00:00Z',
        current_address: 'Toronto, ON',
        employer: 'Retail Inc',
        monthly_income: 3000,
        move_in_date: '2026-02-15',
        num_occupants: 1,
        has_pets: true,
        pet_details: '2 large dogs',
        additional_notes: null,
        screening_status: 'completed',
        credit_score: 600,
        background_check_passed: true,
        income_verified: true,
        screening_report_url: 'http://example.com/report3',
        screening_completed_at: '2026-01-26T10:00:00Z',
        webhook_sent: false,
        webhook_sent_at: null,
        updated_at: '2026-01-26T11:00:00Z',
        agent_id: null,
        company_id: null
    },
    {
        id: 'a5',
        property_id: 'p10',
        applicant_name: 'Robert Wilson',
        applicant_email: 'rob.w@email.com',
        applicant_phone: '416-555-1005',
        status: 'new',
        created_at: '2026-01-28T16:00:00Z',
        current_address: 'Vancouver, BC',
        employer: 'Remote Tech',
        monthly_income: 12000,
        move_in_date: '2026-03-01',
        num_occupants: 2,
        has_pets: false,
        pet_details: null,
        additional_notes: 'Moving from Vancouver.',
        screening_status: 'pending',
        credit_score: null,
        background_check_passed: null,
        income_verified: null,
        screening_report_url: null,
        screening_completed_at: null,
        webhook_sent: false,
        webhook_sent_at: null,
        updated_at: '2026-01-28T16:00:00Z',
        agent_id: null,
        company_id: null
    },
    {
        id: 'a6',
        property_id: 'p4',
        applicant_name: 'Jennifer Lee',
        applicant_email: 'jen.lee@email.com',
        applicant_phone: '416-555-1006',
        status: 'withdrawn',
        created_at: '2026-01-20T09:00:00Z',
        current_address: 'Toronto, ON',
        employer: 'Hospital',
        monthly_income: 5500,
        move_in_date: '2026-02-01',
        num_occupants: 1,
        has_pets: false,
        pet_details: null,
        additional_notes: 'Found another place.',
        screening_status: 'pending',
        credit_score: null,
        background_check_passed: null,
        income_verified: null,
        screening_report_url: null,
        screening_completed_at: null,
        webhook_sent: false,
        webhook_sent_at: null,
        updated_at: '2026-01-22T10:00:00Z',
        agent_id: null,
        company_id: null
    },
    {
        id: 'a7',
        property_id: 'p12',
        applicant_name: 'David Kim',
        applicant_email: 'd.kim@email.com',
        applicant_phone: '647-555-1007',
        status: 'new',
        created_at: '2026-01-29T08:00:00Z',
        current_address: 'Toronto, ON',
        employer: 'University',
        monthly_income: 6800,
        move_in_date: '2026-02-15',
        num_occupants: 2,
        has_pets: false,
        pet_details: null,
        additional_notes: null,
        screening_status: 'pending',
        credit_score: null,
        background_check_passed: null,
        income_verified: null,
        screening_report_url: null,
        screening_completed_at: null,
        webhook_sent: false,
        webhook_sent_at: null,
        updated_at: '2026-01-29T08:00:00Z',
        agent_id: null,
        company_id: null
    },
    {
        id: 'a8',
        property_id: 'p7',
        applicant_name: 'Alex Johnson',
        applicant_email: 'alex.j@email.com',
        applicant_phone: '416-555-1008',
        status: 'screening',
        created_at: '2026-01-27T12:00:00Z',
        current_address: 'Toronto, ON',
        employer: 'StartUp',
        monthly_income: 8000,
        move_in_date: '2026-03-01',
        num_occupants: 1,
        has_pets: true,
        pet_details: 'Small dog',
        additional_notes: null,
        screening_status: 'submitted',
        credit_score: null,
        background_check_passed: null,
        income_verified: null,
        screening_report_url: null,
        screening_completed_at: null,
        webhook_sent: false,
        webhook_sent_at: null,
        updated_at: '2026-01-27T12:00:00Z',
        agent_id: null,
        company_id: null
    }
];

export const DEMO_DOCUMENTS: Document[] = []; // Started empty or add some past ones if needed

export async function getProperties() {
    return DEMO_PROPERTIES;
}

export async function getLandlords() {
    return DEMO_LANDLORDS;
}

export async function getApplications() {
    return DEMO_APPLICANTS;
}

export async function getProperty(id: string) {
    return DEMO_PROPERTIES.find(p => p.id === id);
}

export async function getLandlord(id: string) {
    return DEMO_LANDLORDS.find(l => l.id === id);
}

export async function getLandlordProperties(landlordId: string) {
    return DEMO_PROPERTIES.filter(p => p.landlord_id === landlordId);
}
