export const PLANS = {
    // LEGACY ALIASES — these map to the new plan IDs so old DB values still work
    essentials: {
        id: 'agent_pro',
        name: 'Agent Pro',
        firstMonthPrice: 14900,
        monthlyPrice: 14900,
        limits: {
            properties: 25,
            teamMembers: 1,
        },
        features: {
            dashboard: true,
            properties: true,
            applications: true,
            documents: true,
            basicReporting: true,
            emailSupport: true,
            areas: false,
            approvals: false,
            leases: false,
            maintenance: false,
            showings: false,
            invoices: false,
            analytics: false,
            activity: false,
            automations: false,
            social: true,
            tenantPortal: false,
            paymentProcessing: false,
            customIntegrations: false,
            prioritySupport: false,
        },
        nav: [
            'dashboard',
            'properties',
            'applications',
            'documents',
            'social',
            'settings',
        ],
    },
    professional: {
        id: 'agency_growth',
        name: 'Agency Growth',
        firstMonthPrice: 28900,
        monthlyPrice: 28900,
        limits: {
            properties: 100,
            teamMembers: 5,
        },
        features: {
            dashboard: true,
            properties: true,
            applications: true,
            documents: true,
            basicReporting: true,
            emailSupport: true,
            areas: true,
            approvals: true,
            leases: true,
            maintenance: true,
            showings: true,
            invoices: true,
            analytics: true,
            activity: true,
            automations: true,
            social: true,
            tenantPortal: true,
            paymentProcessing: true,
            customIntegrations: false,
            prioritySupport: false,
        },
        nav: [
            'dashboard',
            'areas',
            'properties',
            'applications',
            'approvals',
            'leases',
            'maintenance',
            'showings',
            'invoices',
            'documents',
            'analytics',
            'activity',
            'social',
            'automations',
            'settings',
        ],
    },
    enterprise: {
        id: 'brokerage_command',
        name: 'Brokerage Command',
        firstMonthPrice: 49900,
        monthlyPrice: 49900,
        limits: {
            properties: Infinity,
            teamMembers: Infinity,
        },
        features: {
            dashboard: true,
            properties: true,
            applications: true,
            documents: true,
            basicReporting: true,
            emailSupport: true,
            areas: true,
            approvals: true,
            leases: true,
            maintenance: true,
            showings: true,
            invoices: true,
            analytics: true,
            activity: true,
            automations: true,
            social: true,
            tenantPortal: true,
            paymentProcessing: true,
            customIntegrations: true,
            prioritySupport: true,
        },
        nav: [
            'dashboard',
            'areas',
            'properties',
            'applications',
            'approvals',
            'leases',
            'maintenance',
            'showings',
            'invoices',
            'documents',
            'analytics',
            'activity',
            'social',
            'automations',
            'settings',
        ],
    },

    // NEW PLAN IDS — these are what Stripe checkout now uses
    agent_pro: {} as any,       // Will be filled below
    agency_growth: {} as any,
    brokerage_command: {} as any,
} as const;

// Create aliases so new plan IDs resolve to the same config
(PLANS as any).agent_pro = PLANS.essentials;
(PLANS as any).agency_growth = PLANS.professional;
(PLANS as any).brokerage_command = PLANS.enterprise;

export type PlanId = keyof typeof PLANS;
export type FeatureKey = keyof typeof PLANS.essentials.features;
