export const PLANS = {
    essentials: {
        id: 'essentials',
        name: 'Essentials',
        firstMonthPrice: 900,
        monthlyPrice: 2900,
        limits: {
            properties: 25,
            teamMembers: 1,
        },
        features: {
            dashboard: true,
            properties: true,
            applications: true,
            documents: true,
            basicReporting: true,
            emailSupport: true,
            areas: false,
            approvals: false,
            leases: false,
            maintenance: false,
            showings: false,
            invoices: false,
            analytics: false,
            activity: false,
            automations: false,
            tenantPortal: false,
            paymentProcessing: false,
            customIntegrations: false,
            prioritySupport: false,
        },
        nav: [
            'dashboard',
            'properties',
            'applications',
            'documents',
            'settings',
        ],
    },
    professional: {
        id: 'professional',
        name: 'Professional',
        firstMonthPrice: 1900,
        monthlyPrice: 4900,
        limits: {
            properties: 100,
            teamMembers: 5,
        },
        features: {
            dashboard: true,
            properties: true,
            applications: true,
            documents: true,
            basicReporting: true,
            emailSupport: true,
            areas: true,
            approvals: true,
            leases: true,
            maintenance: true,
            showings: true,
            invoices: true,
            analytics: true,
            activity: true,
            automations: true,
            tenantPortal: true,
            paymentProcessing: true,
            customIntegrations: false,
            prioritySupport: false,
        },
        nav: [
            'dashboard',
            'areas',
            'properties',
            'applications',
            'approvals',
            'leases',
            'maintenance',
            'showings',
            'invoices',
            'documents',
            'analytics',
            'activity',
            'automations',
            'settings',
        ],
    },
    enterprise: {
        id: 'enterprise',
        name: 'Enterprise',
        firstMonthPrice: 3900,
        monthlyPrice: 7900,
        limits: {
            properties: Infinity,
            teamMembers: Infinity,
        },
        features: {
            dashboard: true,
            properties: true,
            applications: true,
            documents: true,
            basicReporting: true,
            emailSupport: true,
            areas: true,
            approvals: true,
            leases: true,
            maintenance: true,
            showings: true,
            invoices: true,
            analytics: true,
            activity: true,
            automations: true,
            tenantPortal: true,
            paymentProcessing: true,
            customIntegrations: true,
            prioritySupport: true,
        },
        nav: [
            'dashboard',
            'areas',
            'properties',
            'applications',
            'approvals',
            'leases',
            'maintenance',
            'showings',
            'invoices',
            'documents',
            'analytics',
            'activity',
            'automations',
            'settings',
        ],
    },
} as const;

export type PlanId = keyof typeof PLANS;
export type FeatureKey = keyof typeof PLANS.essentials.features;
